// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_vW1jNBvcD6zRoq9lf1jQBVxSsZtIpEM',
    appId: '1:98153141169:web:7fe074049678f87d6fe390',
    messagingSenderId: '98153141169',
    projectId: 'first-app-9395e',
    authDomain: 'first-app-9395e.firebaseapp.com',
    storageBucket: 'first-app-9395e.firebasestorage.app',
    measurementId: 'G-S098MH2GK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASfRdwjmsplufbeLOfMRQbiYthaR1vfhI',
    appId: '1:98153141169:android:dbb865eb1c5f01ef6fe390',
    messagingSenderId: '98153141169',
    projectId: 'first-app-9395e',
    storageBucket: 'first-app-9395e.firebasestorage.app',
  );
}