// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYZYGLGKF8lUXF05Re3xsyUBKwGFbky4E',
    appId: '1:710333161203:web:cdd83b0d4b9184199c6186',
    messagingSenderId: '710333161203',
    projectId: 'firstproject-68546',
    authDomain: 'firstproject-68546.firebaseapp.com',
    storageBucket: 'firstproject-68546.firebasestorage.app',
    measurementId: 'G-9HTHFE2K36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNBCUddFQKysKegtueKQsEiMyNecy0OXE',
    appId: '1:710333161203:android:e061e0f4b4ba3caa9c6186',
    messagingSenderId: '710333161203',
    projectId: 'firstproject-68546',
    storageBucket: 'firstproject-68546.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaw1wpMT-6J_lRs3dbeYDxnmMfYcb6Lqc',
    appId: '1:710333161203:ios:119cbee2cd43fcc99c6186',
    messagingSenderId: '710333161203',
    projectId: 'firstproject-68546',
    storageBucket: 'firstproject-68546.firebasestorage.app',
    iosBundleId: 'com.example.cepuApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaw1wpMT-6J_lRs3dbeYDxnmMfYcb6Lqc',
    appId: '1:710333161203:ios:119cbee2cd43fcc99c6186',
    messagingSenderId: '710333161203',
    projectId: 'firstproject-68546',
    storageBucket: 'firstproject-68546.firebasestorage.app',
    iosBundleId: 'com.example.cepuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYZYGLGKF8lUXF05Re3xsyUBKwGFbky4E',
    appId: '1:710333161203:web:f8c4ddf3c4ce9f7e9c6186',
    messagingSenderId: '710333161203',
    projectId: 'firstproject-68546',
    authDomain: 'firstproject-68546.firebaseapp.com',
    storageBucket: 'firstproject-68546.firebasestorage.app',
    measurementId: 'G-Z7TXZ1SPDK',
  );

}