// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZTg_6dOAqF_DPP5U6_jvVI5I1dWZsx2U',
    appId: '1:960874805382:web:0202013f1b7db07fa7f907',
    messagingSenderId: '960874805382',
    projectId: 'notess-4a553',
    authDomain: 'notess-4a553.firebaseapp.com',
    storageBucket: 'notess-4a553.firebasestorage.app',
    measurementId: 'G-ECD6D1PLNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBijjhpdFiftQHuItux2IpAP6AWGpvMZWE',
    appId: '1:960874805382:android:7267ff3310aba7a8a7f907',
    messagingSenderId: '960874805382',
    projectId: 'notess-4a553',
    storageBucket: 'notess-4a553.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChyJMcSDEalq7-jE158PJzkZ7e_CbVgmw',
    appId: '1:960874805382:ios:19895dddee5eb666a7f907',
    messagingSenderId: '960874805382',
    projectId: 'notess-4a553',
    storageBucket: 'notess-4a553.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChyJMcSDEalq7-jE158PJzkZ7e_CbVgmw',
    appId: '1:960874805382:ios:19895dddee5eb666a7f907',
    messagingSenderId: '960874805382',
    projectId: 'notess-4a553',
    storageBucket: 'notess-4a553.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZTg_6dOAqF_DPP5U6_jvVI5I1dWZsx2U',
    appId: '1:960874805382:web:06e3a3dff56d2556a7f907',
    messagingSenderId: '960874805382',
    projectId: 'notess-4a553',
    authDomain: 'notess-4a553.firebaseapp.com',
    storageBucket: 'notess-4a553.firebasestorage.app',
    measurementId: 'G-7WTS4K294S',
  );
}
